name: Build - Windows

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        buildtype: [windows-release]
        include:
        - os: windows-2022
          triplet: x64-windows
          packages: >
            sccache #magic___^_^___line
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: CCache
      uses: hendrikmuhs/ccache-action@main
      with:
        max-size: "1G"
        variant: "sccache"
        key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
        restore-keys: |
          ccache-${{ matrix.os }}

    - name: Restore artifacts and install vcpkg
      id: vcpkg-step
      run: |
        $json=Get-Content vcpkg.json -Raw | ConvertFrom-Json
        $vcpkgCommitId=$json.'builtin-baseline'
        Write-Host "vcpkg commit ID: $vcpkgCommitId"
        echo "vcpkgGitCommitId=$vcpkgCommitId" >> "$GITHUB_OUTPUT"

    - name: Get vcpkg commit id from vcpkg.json
      uses: lukka/run-vcpkg@main
      with:
        vcpkgGitURL: "https://github.com/microsoft/vcpkg.git"
        vcpkgGitCommitId: ${{ steps.vcpkg-step.outputs.vcpkgGitCommitId }}

    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@main

    - name: Run CMake
      uses: lukka/run-cmake@main
      with:
        configurePreset: ${{ matrix.buildtype }}
        buildPreset: ${{ matrix.buildtype }}

    - name: Create and Upload Artifact (exe)
      uses: actions/upload-artifact@main
      with:
        name: otclient-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
        path: |
          ${{ github.workspace }}/otclient.exe

    - name: Create Temporary Directory
      run: |
        $tempDir = "$env:GITHUB_WORKSPACE/tempDir"
        New-Item -Path $tempDir -ItemType Directory -Force

    - name: Move Files to Temporary Directory
      run: |
        # Move the desired files into the temporary directory
        Move-Item -Path "$env:GITHUB_WORKSPACE/data" -Destination "$env:GITHUB_WORKSPACE/tempDir" -Recurse -Force
        Move-Item -Path "$env:GITHUB_WORKSPACE/mods" -Destination "$env:GITHUB_WORKSPACE/tempDir" -Recurse -Force
        Move-Item -Path "$env:GITHUB_WORKSPACE/modules" -Destination "$env:GITHUB_WORKSPACE/tempDir" -Recurse -Force
        Move-Item -Path "$env:GITHUB_WORKSPACE/init.lua" -Destination "$env:GITHUB_WORKSPACE/tempDir" -Force

    - name: Upload Temporary Directory
      uses: actions/upload-artifact@main
      with:
        name: release-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
        path: ${{ github.workspace }}/tempDir

    - name: Clean Up
      run: |
        Remove-Item -Path "$env:GITHUB_WORKSPACE/tempDir" -Recurse -Force
